### ISSUE TITLE
TameMyCerts.dll not found on install

### ISSUE THREAD

**Issue by georg-x** [Sleepw4lker/TameMyCerts#1]
We tried to install the package as described in the readme:
.\Install.ps1 -PolicyDirectory d:\PKIDATA\Policy
Installation was started as Administrator.
Which directly leads to this errors. Nothing in the Directory. ADCS not starting up anymore.

```
Copy-Item : Cannot find path 'D:\user\TameMyCerts-main\TameMyCerts\TameMyCerts.dll' because it does not exist.
At D:\user\TameMyCerts-main\TameMyCerts\install.ps1:173 char:13
+             Copy-Item -Path $SourcePath -Destination $Path -Force
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (D:\user\TameM...TameMyCerts.dll:String) [Copy-Item], ItemNotFoundExce
   ption
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand

Copy-Item : Cannot find path 'D:\user\TameMyCerts-main\TameMyCerts\TameMyCerts.dll' because it does not exist.
At D:\user\TameMyCerts-main\TameMyCerts\install.ps1:173 char:13
+             Copy-Item -Path $SourcePath -Destination $Path -Force
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (D:\user\TameM...TameMyCerts.dll:String) [Copy-Item], ItemNotFoundExce
   ption
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand


Success Message
------- -------
   True The operation was successful.

```

**Comment by georg-x** [comment]
CA was fixed by reenabling the original Policy in the Registry.
```
[HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\CertSvc\Configuration\CANAME\PolicyModules]
"Active"="CertificateAuthority_MicrosoftDefault.Policy"
```
![image](https://user-images.githubusercontent.com/6449032/170999720-589afe62-4fc0-4564-b02f-2a25af6054a6.png)
Problem with missing dll still exists.

**Comment by Sleepw4lker** [comment]
Hi georg. Seems you cloned the git repository (which only contains the source code) instead of downloading the binary package (which contains a signed version of the DLL - see [releases](https://github.com/Sleepw4lker/TameMyCerts/releases/tag/1.1.432.1215)). I'll ensure that the install script won't do anything when the DLL is not available in the next release ;). Kind regards, and feel free to contact me if you need further assistance.

**Comment by georg-x** [comment]
Thank you for your quick reply. You're right, I fetched the ZIP from GIT repo...
I'll retry with the release file.
A check would be nice...
