### ISSUE TITLE
Special characters in the template name cause a problem in TameMyCerts

### ISSUE THREAD

**Issue by PaulBlenderman** [Sleepw4lker/TameMyCerts#16]
While testing something else, I created a template named UserÜöäß/&|(). A certificate request based on the template was denied until I told the CA to no longer use TameMyCerts.
Two events were reported:

```
04/08/2023 10:52:25 53 Warning          Active Directory Certificate Services denied request xx because The parameter
                                        is incorrect. 0x80070057 (WIN32: 87 ERROR_INVALID_PARAMETER).  The request was
                                        for xxx\xxx.  Additional information: Denied by Policy Module
04/08/2023 10:52:24 77 Warning          The "TameMyCerts" Policy Module logged the following warning: The Active
                                        Directory connection to xxx has been reestablished to xxx.
```

Sorry, I have not tested which of the characters /, &, |, ( or ) in the template name cause the problem.
TameMyCerts itself does not log an event.

**Comment by Sleepw4lker** [comment]
Hello @PaulBlenderman thanks for your feedback. This is because the template name contains characters that are not valid for file name. Because this is not properly handled, it causes the verification process to crash. I was able to reproduce this and will include a fix in the upcoming version.
