### ISSUE TITLE
Customizing DNs in TameMyCerts

### ISSUE THREAD

**Issue by FZJALAL** [Sleepw4lker/TameMyCerts#18]
Hello friends!
I hope you are doing well. I'm reaching out to you because I recently came across your TameMyCerts solution on GitHub, and I'm very impressed with its features. I'm currently facing a specific challenge related to customizing Distinguished Names (DN) during certificate creation.

My issue is as follows: I am working with a Certificate Management System (CMS) that automatically generates Certificate Signing Requests (CSR) containing a DN. Within this DN, there is a Serial Number (SN) generated by the CMS. These CSRs are then sent to a Certificate Authority for signing, following the rules defined by the TameMyCerts policy module.

What I am looking to achieve is to automatically replace the Serial Number (SN) in the DN with a specific Organization Identifier (OI). For instance, if the Serial Number in the CSR is "1234," I would like the issued certificate to display "OI=1234" within the DN.

I believe your TameMyCerts solution could be tailored to meet this requirement, but I am unsure of the best approach to accomplish this. I am willing to discuss the technical details to obtain assistance in implementing this customization.

**Comment by Sleepw4lker** [comment]
Hello Fatimazahrae,

thanks for reaching out.

I am currently working on the next version of the module which already allows to build DN or SAN components based on configurable rules, like inserting AD or request properties into a string. It could easily be extended to include, lets say replacement rules based on regular expressions.

Which leads me to the question if you could further specify your requirements. Could they be solved with a regex based ruleset, or is it more complicated?

Feel free to reach out to me to discuss this further.

Cheers
Uwe
