### ISSUE TITLE
Renew results in Error 0x80131500 (-2146233088) 

### ISSUE THREAD

**Issue by kruhmann** [Sleepw4lker/TameMyCerts#20]
Hi, an exception is thrown when a certificate is renewed. It can be reproduced by creating an offline template with CA Manager Approval and configure "Valid existing certificate" in Issuance Requirements. When a CSR with subject and SAN is created it works. Tested with certlm.msc: Create CSR and retrieve certificate (Approval required). Then manual "Renew Certificate with new Key".

But when the SAN is **omitted** (Subject only), then the request is denied:
![image](https://github.com/Sleepw4lker/TameMyCerts/assets/9945612/7e3a7213-585f-440f-9b65-aed0bfd8ab80)

Maybe due an emtpy SAN, which appears during renewal:
![image](https://github.com/Sleepw4lker/TameMyCerts/assets/9945612/ca736d35-89a4-422f-ae96-6fc80afea84a)

I tested it on Win2k19 with TameMyCerts 1.6.1045.1129.

Kind regards
Konstantin

**Comment by Sleepw4lker** [comment]
Hello @kruhmann, thank you very much for submitting. My time is currently limited, but I put this on the ToDo list for the next version.
