### ISSUE TITLE
Event source is not removed on uninstall

### ISSUE THREAD

**Issue by gnugnug** [Sleepw4lker/TameMyCerts#22]
Hello,
great project! A little nitpick: I noticed that the install script creates a Windows event log source named TameMyCerts but doesn't remove it on uninstall. It would be great if the unintall method would clean up all traces.

**Comment by Sleepw4lker** [comment]
Thank you, fixed it.

**Comment by gnugnug** [comment]
@Sleepw4lker Thank you, however [System.Diagnostics.EventLog]::DeleteEventSource() only takes one argument, not two: https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.eventlog.deleteeventsource
