### ISSUE TITLE
Clarification in the documentation about generated logs

### ISSUE THREAD

**Issue by gnugnug** [Sleepw4lker/TameMyCerts#27]
The documentation https://docs.tamemycerts.com/#logs states:
"_Events 1 and 11 occur only if the certification authoritys LogLevel setting is configured to 4 (CERTLOG_VERBOSE) or higher._" needs to be updated as well.

As far as I can see this applies to event ID 7 as well, which has log level Verbose.

**Comment by Sleepw4lker** [comment]
Thank you, I'll fix this in the docs.
